# Generated by Django 4.2.4 on 2023-11-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
            ],
        ),
    ]
