# Generated by Django 4.2.4 on 2023-11-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsolat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kala',
            old_name='titel',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='kala',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kala',
            name='img',
            field=models.ImageField(upload_to='aks'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='price',
            field=models.TextField(),
        ),
    ]
